import { useState } from "react";
import { Copy, Check, RefreshCw, ThumbsUp, ThumbsDown, Pencil, Share2, Download, MessageCircle, Mail, FileText, FileDown, Bookmark } from "lucide-react";
import { Button } from "./ui/button";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./ui/tooltip";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuLabel,
} from "./ui/dropdown-menu";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import { jsPDF } from "jspdf";

interface MessageActionsProps {
  messageId: string;
  content: string;
  role: "user" | "assistant";
  isLastAssistant?: boolean;
  isLastUser?: boolean;
  onRegenerate?: () => void;
  onEdit?: () => void;
  feedback?: "positive" | "negative" | null;
  onFeedbackChange?: (feedback: "positive" | "negative" | null) => void;
  conversationId?: string;
}

export function MessageActions({
  messageId,
  content,
  role,
  isLastAssistant = false,
  isLastUser = false,
  onRegenerate,
  onEdit,
  feedback: initialFeedback,
  onFeedbackChange,
  conversationId,
}: MessageActionsProps) {
  const [copied, setCopied] = useState(false);
  const [feedback, setFeedback] = useState<"positive" | "negative" | null>(initialFeedback || null);
  const [isSubmittingFeedback, setIsSubmittingFeedback] = useState(false);
  const [isBookmarked, setIsBookmarked] = useState(false);
  const { user } = useAuth();

  // Check bookmark status on mount
  useState(() => {
    if (role === "assistant" && user && messageId !== "streaming") {
      supabase.from("bookmarks").select("id").eq("user_id", user.id).eq("message_id", messageId).maybeSingle().then(({ data }) => {
        if (data) setIsBookmarked(true);
      });
    }
  });

  const handleBookmark = async () => {
    if (!user || !conversationId) return;
    if (isBookmarked) {
      await supabase.from("bookmarks").delete().eq("user_id", user.id).eq("message_id", messageId);
      setIsBookmarked(false);
      toast.success("Bookmark removed");
    } else {
      await supabase.from("bookmarks").insert({ user_id: user.id, message_id: messageId, conversation_id: conversationId });
      setIsBookmarked(true);
      toast.success("Response saved!");
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy");
    }
  };

  const handleFeedback = async (type: "positive" | "negative") => {
    if (!user || isSubmittingFeedback) return;

    setIsSubmittingFeedback(true);
    const newFeedback = feedback === type ? null : type;

    try {
      if (newFeedback === null) {
        // Remove feedback
        await supabase
          .from("message_feedback")
          .delete()
          .eq("message_id", messageId)
          .eq("user_id", user.id);
      } else if (feedback) {
        // Update existing feedback
        await supabase
          .from("message_feedback")
          .update({ feedback: newFeedback })
          .eq("message_id", messageId)
          .eq("user_id", user.id);
      } else {
        // Insert new feedback
        await supabase
          .from("message_feedback")
          .insert({ message_id: messageId, user_id: user.id, feedback: newFeedback });
      }

      setFeedback(newFeedback);
      onFeedbackChange?.(newFeedback);
    } catch (error) {
      console.error("Failed to submit feedback:", error);
      toast.error("Failed to submit feedback");
    } finally {
      setIsSubmittingFeedback(false);
    }
  };

  const isUser = role === "user";

  const handleShareWhatsApp = () => {
    const text = encodeURIComponent(`From Santra Health:\n\n${content}\n\nhttps://santra-health.lovable.app`);
    window.open(`https://wa.me/?text=${text}`, "_blank");
  };

  const handleShareEmail = () => {
    const subject = encodeURIComponent("Shared from Santra Health");
    const body = encodeURIComponent(`${content}\n\n— Shared via Santra Health\nhttps://santra-health.lovable.app`);
    window.open(`mailto:?subject=${subject}&body=${body}`, "_blank");
  };

  const handleDownloadText = () => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "santra-response.txt";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded as text file");
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(12);
    const lines = doc.splitTextToSize(content, 170);
    doc.text(lines, 20, 20);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Santra Health — santra-health.lovable.app", 20, 285);
    doc.save("santra-response.pdf");
    toast.success("Downloaded as PDF");
  };

  return (
    <TooltipProvider delayDuration={300}>
      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
        {/* Copy button - for all messages */}
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7 text-muted-foreground hover:text-foreground"
              onClick={handleCopy}
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
            </Button>
          </TooltipTrigger>
          <TooltipContent side="bottom">
            <p>{copied ? "Copied!" : "Copy"}</p>
          </TooltipContent>
        </Tooltip>

        {/* Edit button - for user messages */}
        {isUser && isLastUser && onEdit && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7 text-muted-foreground hover:text-foreground"
                onClick={onEdit}
              >
                <Pencil size={14} />
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">
              <p>Edit</p>
            </TooltipContent>
          </Tooltip>
        )}

        {/* Regenerate button - for assistant messages */}
        {!isUser && isLastAssistant && onRegenerate && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7 text-muted-foreground hover:text-foreground"
                onClick={onRegenerate}
              >
                <RefreshCw size={14} />
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">
              <p>Regenerate</p>
            </TooltipContent>
          </Tooltip>
        )}

        {/* Share & Download - for assistant messages */}
        {!isUser && (
          <DropdownMenu>
            <Tooltip>
              <TooltipTrigger asChild>
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-7 w-7 text-muted-foreground hover:text-foreground"
                  >
                    <Share2 size={14} />
                  </Button>
                </DropdownMenuTrigger>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                <p>Share & Download</p>
              </TooltipContent>
            </Tooltip>
            <DropdownMenuContent align="start" className="w-48">
              <DropdownMenuLabel className="text-xs">Share</DropdownMenuLabel>
              <DropdownMenuItem onClick={handleShareWhatsApp} className="gap-2 cursor-pointer">
                <MessageCircle className="h-4 w-4" />
                WhatsApp
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleShareEmail} className="gap-2 cursor-pointer">
                <Mail className="h-4 w-4" />
                Email
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuLabel className="text-xs">Download</DropdownMenuLabel>
              <DropdownMenuItem onClick={handleDownloadPDF} className="gap-2 cursor-pointer">
                <FileText className="h-4 w-4" />
                Download as PDF
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleDownloadText} className="gap-2 cursor-pointer">
                <FileDown className="h-4 w-4" />
                Download as Text
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        )}

        {/* Feedback buttons - for assistant messages */}
        {!isUser && (
          <>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className={`h-7 w-7 ${
                    feedback === "positive"
                      ? "text-primary bg-primary/10"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                  onClick={() => handleFeedback("positive")}
                  disabled={isSubmittingFeedback}
                >
                  <ThumbsUp size={14} />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                <p>Good response</p>
              </TooltipContent>
            </Tooltip>

            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className={`h-7 w-7 ${
                    feedback === "negative"
                      ? "text-destructive bg-destructive/10"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                  onClick={() => handleFeedback("negative")}
                  disabled={isSubmittingFeedback}
                >
                  <ThumbsDown size={14} />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                <p>Bad response</p>
              </TooltipContent>
            </Tooltip>

            {/* Bookmark button */}
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className={`h-7 w-7 ${
                    isBookmarked
                      ? "text-yellow-500 bg-yellow-500/10"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                  onClick={handleBookmark}
                >
                  <Bookmark size={14} fill={isBookmarked ? "currentColor" : "none"} />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                <p>{isBookmarked ? "Remove bookmark" : "Save response"}</p>
              </TooltipContent>
            </Tooltip>
          </>
        )}
      </div>
    </TooltipProvider>
  );
}
